spring:
    datasource:
        url: jdbc:h2:mem:gamedb
        username: hugo
        password:
    jpa:
        show-sql: true
        open-in-view: false
        hibernate:
            ddl-auto: create # validate | update | create | create-drop
        properties:
            hibernate:
                format_sql: true
                boot:
                    allow_jdbc_metadata_access: true
    sql:
        init:
            mode: never
    h2:
        console:
            enabled: true
            path: /h2-console
            settings:
                trace: false
                web-allow-others: false
                